[package]
name = "meikPod"
version = "0.1.0"
authors = ["li <@li:maisiliym.uniks>"]
edition = "2018"

[dependencies.uniks]
version = "*"
features = []
path = ".."

[dependencies.niks]
version = "*"
features = []
path = "../niks"
