[package]
name = "niks"
version = "0.1.0"
authors = ["li <@li:maisiliym.uniks>"]
edition = "2018"

[features]
default = [  ]

[dependencies.uniks]
version = "*"
features = []
path = "../"

[dependencies.serde]
version = "*"
features = [ "std", "derive" ]

[dependencies.serde_json]
version = "*"
